import { test, expect, type Page } from '@playwright/test';
import fs from 'node:fs/promises';

async function register(page:Page, username:string) {
  await page.goto('/');
  await page.getByRole('button',{name:'Ainda não tenho conta'}).click();
  await page.getByLabel('Usuário',{exact:true}).fill(username);
  await page.getByLabel('Senha',{exact:false}).fill('Caderno-Teste-2026!');
  await page.getByRole('button',{name:'Criar minha conta'}).click();
  await expect(page.getByRole('heading',{name:'Meu caderno',exact:true})).toBeVisible();
}
async function saved(page:Page) {
  await expect(page.locator('.save-actions')).toContainText('Salvo',{timeout:10000});
}
async function step(page:Page, name:string) {
  await page.getByRole('navigation',{name:'Etapas de criação'}).getByRole('button',{name:new RegExp(name+'$')}).click();
}

test('jogador cria, salva, recebe ajustes e aprovação de snapshot, exporta e imprime',async({browser})=>{
  const errors:string[]=[];
  const masterContext = await browser.newContext({viewport:{width:1280,height:900}});
  const playerContext = await browser.newContext({viewport:{width:1280,height:900}});
  const master = await masterContext.newPage(); const player = await playerContext.newPage();
  for(const p of [master,player]) p.on('pageerror',e=>errors.push(e.message));
  const suffix=Date.now().toString();
  await fs.mkdir('../docs/qa',{recursive:true});
  await master.goto('/');
  await master.screenshot({path:'../docs/qa/acesso-desktop.png',fullPage:true});
  await register(master,'mestre-'+suffix);
  await master.getByLabel('Nova campanha').fill('Mesa de teste '+suffix);
  await master.getByRole('button',{name:'Criar como mestre'}).click();
  await expect(master.locator('.campaign-select')).toContainText('Mesa de teste');
  await master.getByRole('button',{name:'Gerar convite de jogador'}).click();
  await expect(master.getByLabel('Convite do mestre')).toHaveValue(/convite=/);
  const link = await master.getByLabel('Convite do mestre').inputValue();
  expect(link).toContain('convite=');
  await register(player,'jogador-'+suffix);
  await player.getByLabel('Convite do mestre').fill(link);
  await player.getByRole('button',{name:'Entrar na campanha'}).click();
  await expect(player.getByRole('button',{name:'Criar personagem'})).toBeEnabled();
  await player.getByRole('button',{name:'Criar personagem'}).click();
  await player.getByLabel('Nome do personagem',{exact:false}).fill('Personagem de teste');
  await player.getByLabel('Quem você quer ser?').fill('Proteger a vila.');
  await saved(player);
  await step(player,'Raça');
  await player.getByLabel('Raça',{exact:false}).fill('Raça manual de teste');
  await saved(player);
  await step(player,'Atributos');
  await player.getByLabel('Força',{exact:true}).fill('3');
  await player.getByLabel('Agilidade',{exact:true}).fill('3');
  await saved(player);
  await expect(player.locator('.points')).toContainText('0');
  await step(player,'Classe');
  await player.getByRole('radio',{name:/Samurai/}).check();
  await saved(player);
  await step(player,'Conferência');
  await expect(player.locator('.sheet-summary .resources')).toContainText('21');
  await player.getByLabel('PV atual',{exact:true}).fill('7');
  await player.getByLabel('PE atual',{exact:true}).fill('2');
  await player.getByLabel('SAN atual',{exact:true}).fill('8');
  await player.getByRole('button',{name:'Salvar recursos atuais'}).click();
  await expect(player.getByRole('status').filter({hasText:'Recursos atuais salvos'})).toBeVisible();
  await player.getByRole('button',{name:'Comparar arquétipos'}).click();
  await expect(player.locator('.archetype-card')).toHaveCount(4);
  await player.screenshot({path:'../docs/qa/comparacao-desktop.png',fullPage:true});
  await player.getByLabel('Vigor',{exact:true}).fill('2');
  await expect(player.locator('.archetype-card').first().locator('.resources')).toContainText('22');
  await player.getByRole('button',{name:'Meu caderno',exact:true}).click();
  await player.getByRole('button',{name:/Personagem de teste/}).click();
  await step(player,'Conferência');
  await expect(player.locator('.sheet-summary .resources')).toContainText('21');
  await step(player,'Revisão');
  await player.getByRole('button',{name:'Enviar ao mestre'}).click();
  await expect(player.getByRole('status').filter({hasText:'Snapshot enviado'})).toBeVisible();
  await master.reload();
  await master.getByRole('button',{name:/Personagem de teste/}).click();
  await step(master,'Revisão');
  await expect(master.getByRole('button',{name:'Aprovar snapshot'})).toBeDisabled();
  await master.getByLabel('Comentário do mestre').fill('Vamos conferir as regras da mesa.');
  await master.getByRole('button',{name:'Solicitar ajustes'}).click();
  await expect(master.locator('.submission')).toContainText('Ajustes solicitados');
  const selector=master.getByLabel('Decisão',{exact:true});
  await selector.selectOption('R06');
  await master.getByLabel('Como tratar duplicatas').fill('Escolher outra perícia.');
  await master.getByLabel('Graus de treinamento').fill('Treinamento manual conferido; sem bônus automático.');
  await master.getByLabel('Motivo e seção da fonte').fill('Decisão sintética para verificar a aplicação.');
  await master.getByRole('button',{name:'Registrar decisão',exact:true}).click();
  await expect(master.getByRole('status').filter({hasText:'Decisão registrada'})).toBeVisible();
  await selector.selectOption('R08');
  await master.getByLabel('Elegibilidade por raça e classe').fill('Esta ficha não tem técnicas.');
  await master.getByLabel('Motivo e seção da fonte').fill('Decisão sintética para teste de revisão.');
  await master.getByRole('button',{name:'Registrar decisão',exact:true}).click();
  await expect(master.getByRole('status').filter({hasText:'Decisão registrada'})).toBeVisible();
  await selector.selectOption('R09');
  await master.getByLabel('Limite após o bônus do Híbrido').fill('Sem bônus racial nesta ficha de teste.');
  await master.getByLabel('Motivo e seção da fonte').fill('Decisão sintética para teste de revisão.');
  await master.getByRole('button',{name:'Registrar decisão',exact:true}).click();
  await expect(master.getByRole('status').filter({hasText:'Decisão registrada'})).toBeVisible();
  await selector.selectOption('RACE');
  await master.getByLabel('Motivo e seção da fonte').fill('Raça manual sem benefícios para este teste.');
  await master.getByRole('button',{name:'Registrar decisão',exact:true}).click();
  await expect(master.getByRole('status').filter({hasText:'Decisão registrada'})).toBeVisible();
  await player.reload();
  await player.getByRole('button',{name:/Personagem de teste/}).click();
  await step(player,'Revisão');
  await player.getByRole('button',{name:'Enviar ao mestre'}).click();
  await expect(player.getByRole('status').filter({hasText:'Snapshot enviado'})).toBeVisible();
  await master.reload();
  await master.getByRole('button',{name:/Personagem de teste/}).click();
  await step(master,'Revisão');
  await expect(master.getByRole('button',{name:'Aprovar snapshot'})).toBeEnabled();
  await master.getByRole('button',{name:'Aprovar snapshot'}).click();
  await expect(master.getByRole('status').filter({hasText:'Revisão aprovada'})).toBeVisible();
  await player.reload();
  await player.getByRole('button',{name:/Personagem de teste/}).click();
  await expect(player.locator('.editor-heading .tag')).toHaveText('Aprovada');
  await step(player,'Conferência');
  const downloadEvent=player.waitForEvent('download');
  await player.getByRole('link',{name:'Exportar JSON salvo'}).click();
  const download=await downloadEvent;
  const downloaded=await fs.readFile((await download.path())!,'utf8');
  const exported=JSON.parse(downloaded);
  expect(exported.approved).toBe(true);expect(exported.resourceState.pv).toBe(7);expect(exported.validation.maxima.pv).toBe(21);
  await player.emulateMedia({media:'print'});
  await expect(player.locator('.print-sheet')).toBeVisible();
  await player.pdf({path:'../test-results/impressao.pdf',format:'A4'});
  await player.emulateMedia({media:'screen'});
  await player.setViewportSize({width:360,height:800});
  await step(player,'Atributos');
  await player.screenshot({path:'../docs/qa/ficha-mobile.png',fullPage:true});
  expect(await player.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(360);
  await player.getByLabel('Força',{exact:true}).focus();
  await expect(player.getByLabel('Força',{exact:true})).toBeFocused();
  await step(player,'Conceito');
  await player.getByLabel('Quem você quer ser?').fill('Conceito alterado depois da aprovação.');
  await saved(player);
  await expect(player.locator('.editor-heading .tag')).toHaveText('Em construção');
  expect(errors).toEqual([]);
  await masterContext.close();await playerContext.close();
});

test('falha no salvamento e conflito preservam a edição local',async({page})=>{
  await register(page,'conflito-'+Date.now());
  await page.getByLabel('Nova campanha').fill('Teste de conflito');
  await page.getByRole('button',{name:'Criar como mestre'}).click();
  await expect(page.getByRole('button',{name:'Criar personagem'})).toBeEnabled();
  await page.getByRole('button',{name:'Criar personagem'}).click();
  await page.route('**/api/characters/*',async route=>{
    if(route.request().method()==='PATCH') return route.abort('failed');
    await route.continue();
  });
  await page.getByLabel('Nome do personagem',{exact:false}).fill('Edição preservada');
  await expect(page.getByRole('alert')).toBeVisible();
  await expect(page.getByLabel('Nome do personagem',{exact:false})).toHaveValue('Edição preservada');
  await page.unroute('**/api/characters/*');
  await page.getByRole('button',{name:'Salvar agora'}).click();
  await saved(page);
  await page.route('**/api/characters/*',async route=>{
    if(route.request().method()==='PATCH') return route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({detail:'Conflito de teste'})});
    await route.continue();
  });
  await page.getByLabel('Nome do personagem',{exact:false}).fill('Alteração em conflito');
  await expect(page.locator('.save-actions')).toContainText('Conflito de edição');
  await expect(page.getByLabel('Nome do personagem',{exact:false})).toHaveValue('Alteração em conflito');
  await expect(page.getByRole('button',{name:'Ver versão salva'})).toBeVisible();
});
